### ISSUE TITLE
Accessing local file storage

### ISSUE THREAD

**Issue by loldrup** [maks/MGit#110]
I have cloned my repository 'myRepo', using
/storage/emulated/0/myRepos
as my 'Root storage location for repos', and using 'myRepo' as the 'Local Path' during the cloning operation.
Even so, I can see no files in /storage/emulated/0/myRepos/myRepo
The folder 'myRepo' was created during the cloning, but it is very empty. Where are my repository files?

**Comment by maks** [comment]
Thanks for filing this issue and sorry about the poor state of error reporting at the moment in MGit, it one of my top priority issues to fix in the next release.
If your repo is available publicly, could you include it here as then I can try to replicate the issue. Otherwise could you let me know if its a large repo (> 50MB)? And also could you please include the device and version on Android you are using.

**Comment by loldrup** [comment]
Today when I looked in the folder the files had shown up!
I then tried cloning another repository ( size: 136kb ) and its files showed up immediately. Thus I cannot reproduce the error at this time.
The repository that failed yesterday had a size of 8mb

**Comment by dcrisp2** [comment]
Found myself in a similar situation yesterday. I didnt actually time my checks, but I looked for it as soon as MGIT seemed to indicate it had finished cloning, then again about 10 min. later. It wasn't until I looked again about two hours later that I saw my repos contents. Maybe there's an index of the Android filesystem that could be updated on clone completion?

**Comment by psibi** [comment]
I think this happens only first time. I installed the app and in my first clone, I was not able to see any files. I deleted the repo and re-cloned again and everything worked fine.

**Comment by gbrand-salesforce** [comment]
For some reason, MGit had its storage permissions disabled after installation... I had to got to App Settings, choose MGit and enable the storage permission. It appears to have stored the repo internally... I've deleted it and recloned again, but couldn't see it anywhere, again...

Then, I entered the MGit settings and set the root directory to /storage/emulated/0/git (made a new dir), after selecting to set as root dir I got the following error

```
USER_COMMENT=
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=1.5.4.2
BRAND=samsung
PHONE_MODEL=SM-G950F
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
at me.sheimi.sgit.database.models.Repo.setLocalRepoRoot(Repo.java:525)
at me.sheimi.sgit.activities.explorer.ExploreRootDirActivity.onOptionsItemSelected(ExploreRootDirActivity.java:68)
at android.app.Activity.onMenuItemSelected(Activity.java:3527)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:675)
at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
at android.widget.AdapterView.performItemClick(AdapterView.java:350)
at android.widget.AbsListView.performItemClick(AbsListView.java:1683)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:4094)
at android.widget.AbsListView$10.run(AbsListView.java:6583)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
The second time, it let me select the folder... But I ket getting that same error whenever I clicked on my cloned repo. 

Deleted the clone a second time, cloned again - and now it worked... So I guess it's all to do with the fact the permissions weren't granted during installation (I wasn't asked about them).

**Comment by kaeptmblaubaer1000** [comment]
@gbrand-salesforce this maybe happens because the external storage permission is only granted when MGit would ask for it. If you'd try with Android < 5.0, it'd probably work.

**Comment by dispasha** [comment]
Thank you, had the same issue
