### ISSUE TITLE
NPE in showException

### ISSUE THREAD

**Issue by maks** [maks/MGit#147]
from Play crash reports:
```
java.lang.NullPointerException
	at me.sheimi.android.utils.BasicFunctions.showException(BasicFunctions.java:78)
	at me.sheimi.sgit.repo.tasks.SheimiAsyncTask.showError(SheimiAsyncTask.java:22)
	at me.sheimi.sgit.repo.tasks.repo.RepoOpTask.onPostExecute(RepoOpTask.java:26)
	at me.sheimi.sgit.repo.tasks.repo.CommitDiffTask.onPostExecute(CommitDiffTask.java:73)
	at me.sheimi.sgit.repo.tasks.repo.CommitDiffTask.onPostExecute(CommitDiffTask.java:28)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4929)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by maks** [comment]
Fixed in 818fa9628b3b3b1f5f36d46fdc050c33aff87ca1
