### ISSUE TITLE
Error when cloning: Exception caught during execution of fetch command

### ISSUE THREAD

**Issue by smorar** [maks/MGit#161]
When adding a SSH repository in the Clone Repository dialog as follows,
ssh://server:/home/smorar/pathtorepo
I get an error which reads "Exception caught during execution of fetch command".
This occurs with and without adding my authentication details.

**Comment by maks** [comment]
Thanks for reporting the issue. Could you try using the alternative syntax, eg.
`git@server:/home/smorar/pathtorepo`
to see if that works for you instead?
If not, could you please include here the full error stack trace text you see when you get the error dialog.

**Comment by smorar** [comment]
The alternative syntax now fails with "Auth cancel".
When looking at my server, I get the following logged in /var/log/auth.log

> May 22 20:01:53 arya sshd[1248]: error: Received disconnect from 192.168.1.249 port 46368:3: com.jcraft.jsch.JSchException: Auth cancel [preauth]
> May 22 20:01:53 arya sshd[1248]: Disconnected from 192.168.1.249 port 46368 [preauth]

**Comment by maks** [comment]
Thanks for checking that. Its hard to tell from that specifically what is going wrong, could you please provide the full stacktrace displayed by MGit?

**Comment by smorar** [comment]
Here's a stack trace from using your recommended syntax:

>05-25 20:41:31.165 23327 23327 W System.err: org.eclipse.jgit.api.errors.TransportException: smorar@arya:/home/smorar/Sparkleshare/Literature: Auth cancel
05-25 20:41:31.168 23327 23327 W System.err: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
05-25 20:41:31.168 23327 23327 W System.err: 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
05-25 20:41:31.168 23327 23327 W System.err: 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
05-25 20:41:31.168 23327 23327 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:73)
05-25 20:41:31.168 23327 23327 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:35)
05-25 20:41:31.168 23327 23327 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:22)
05-25 20:41:31.168 23327 23327 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-25 20:41:31.168 23327 23327 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 20:41:31.168 23327 23327 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-25 20:41:31.168 23327 23327 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-25 20:41:31.168 23327 23327 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-25 20:41:31.168 23327 23327 W System.err: 	at java.lang.Thread.run(Thread.java:761)
05-25 20:41:31.169 23327 23327 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: smorar@arya:/home/smorar/Sparkleshare/Literature: Auth cancel
05-25 20:41:31.169 23327 23327 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
05-25 20:41:31.169 23327 23327 W System.err: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
05-25 20:41:31.170 23327 23327 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
05-25 20:41:31.170 23327 23327 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
05-25 20:41:31.170 23327 23327 W System.err: 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
05-25 20:41:31.170 23327 23327 W System.err: 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
05-25 20:41:31.170 23327 23327 W System.err: 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
05-25 20:41:31.170 23327 23327 W System.err: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
05-25 20:41:31.170 23327 23327 W System.err: 	... 11 more
05-25 20:41:31.171 23327 23327 W System.err: Caused by: com.jcraft.jsch.JSchException: Auth cancel
05-25 20:41:31.171 23327 23327 W System.err: 	at com.jcraft.jsch.Session.connect(Session.java:511)
05-25 20:41:31.171 23327 23327 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
05-25 20:41:31.171 23327 23327 W System.err: 	... 18 more

Here's the stack trace using the ssh:// syntax:

>05-25 20:45:53.863 23327 23327 W System.err: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:145)
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
05-25 20:45:53.864 23327 23327 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:73)
05-25 20:45:53.864 23327 23327 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:35)
05-25 20:45:53.864 23327 23327 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:22)
05-25 20:45:53.864 23327 23327 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-25 20:45:53.864 23327 23327 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 20:45:53.864 23327 23327 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-25 20:45:53.864 23327 23327 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-25 20:45:53.864 23327 23327 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-25 20:45:53.864 23327 23327 W System.err: 	at java.lang.Thread.run(Thread.java:761)
05-25 20:45:53.864 23327 23327 W System.err: Caused by: org.eclipse.jgit.errors.NotSupportedException: URI not supported: ssh:///arya:/home/smorar/Sparkleshare/Literature
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.transport.Transport.open(Transport.java:564)
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.transport.Transport.open(Transport.java:438)
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.transport.Transport.open(Transport.java:319)
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.transport.Transport.open(Transport.java:288)
05-25 20:45:53.864 23327 23327 W System.err: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:120)
05-25 20:45:53.864 23327 23327 W System.err: 	... 11 more

**Comment by maks** [comment]
Great, thanks for adding this information, that helps.
  
Looking at the docs for [git Urls](https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a) I think the "ssh://" prefix is not the issue - its that currently MGit doesn't use the username entered into the username field (see: #41) so you have to provide the username in the git repo Url.
But this doesnt address why authentication is stilling failing for you even after you do include your username in the url following the example I gave.

Sorry I think I'll need some more information to debug this:
* are you using the current version of MGit in the play store (1.5.2) ?
* what type of auth are you using for this ssh connection, password, private key or private key with passphrase?
* if you are using private key, do you also have a password set for that user on your server hosting the repo and if so can you check trying to clone using just the password without the private key set in MGit (eg. remove private key from MGit temporarily)

**Comment by smorar** [comment]
Responses to your questions:
- are you using the current version of MGit in the play store (1.5.2) ?
>Yes
- what type of auth are you using for this ssh connection, password, private key or private key with passphrase?
>password only
- if you are using private key, do you also have a password set for that user on your server hosting the repo and if so can you check trying to clone using just the password without the private key set in MGit (eg. remove private key from MGit temporarily)
>not applicable, no private key set

**Comment by maks** [comment]
Ok, thanks I think I've identified the issue, its due to recent change to support ssh private keys protected by a passphrase. This has caused MGit when it prompts for user credentials when doing ssh login to assume that they are for a private key passphrase and not ssh login credentials.

In the meantime, I'd suggest the easiest work around is to use a public/private key for users ssh login on the server with the git repo and add that private key into MGit.

MGit already even has a simple UI to generate a keypair and easy means to then copy the public key text to put into your users `.ssh/authorized_keys` file (please ensure your `.ssh` folder and `.ssh/authorized_keys` file have the correct permissions set) .

**Comment by smorar** [comment]
Thank you @maks 
I have managed to get it to work using the keypair as suggested.

**Comment by c0001** [comment]
I have the same problem of it and can not work well with your latest suggestion :
 1.that I use my laptop using key file into Mygit sshkey folder, not working with info "auth cancel".

2.copy the pub_keyfile (created by Mygit) into server of my home, not working too.

I need help.

**Comment by meitar** [comment]
I have the same [problem c0001](https://github.com/maks/MGit/issues/161#issuecomment-320460872) is having.

I know that my SSH setup is correct because I am able to connect successfully to the server with the same user to clone the same repository via the `git` client on my laptop. But mGit fails with an "Auth cancel" message, then shows a UI fragment asking for username/password credentials.

My SSH server does not even accept username/password credentials at all (i.e., `PasswordAuthentication` and `ChallengeResponseAuthentication` are both set to `no` and `PubkeyAuthentication` is set to `yes`) and I have given mGit my unencrypted private key file (i.e., my private key file for this authorized public key does not require a password to unlock or use).

I would really like to access these repositories on my Android device. :(
