### ISSUE TITLE
"Auth fail" when trying to push to a linux PC with ssh running (username + password)

### ISSUE THREAD

**Issue by uvok** [maks/MGit#165]
Hello,

I'm using MGit 1.5.2 from FDroid.
I configured a local repository on my Android Phone (LineageOS 14.1), and later added a linux PC in the same network as remote.
When I try to push to this remote, I get an "Auth Error" toast, as well as a window "Authentication Failed", asking me to re-enter user name + password.
The URL format is according to the [faq](https://github.com/maks/MGit/wiki/faq), `ssh://username@server.com/path/to/repository`.

Logcat states:
```
06-14 19:22:13.962 13219 13219 W System.err: org.eclipse.jgit.api.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
06-14 19:22:13.963 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.pushRepo(PushTask.java:109)
06-14 19:22:13.963 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:43)
06-14 19:22:13.963 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:24)
06-14 19:22:13.963 13219 13219 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-14 19:22:13.963 13219 13219 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.lang.Thread.run(Thread.java:761)
06-14 19:22:13.963 13219 13219 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:320)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:166)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
06-14 19:22:13.964 13219 13219 W System.err: 	at org.eclipse.jgit.transport.Transport.push(Transport.java:1200)
06-14 19:22:13.964 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
06-14 19:22:13.964 13219 13219 W System.err: 	... 9 more
06-14 19:22:13.964 13219 13219 W System.err: Caused by: com.jcraft.jsch.JSchException: Auth fail
06-14 19:22:13.964 13219 13219 W System.err: 	at com.jcraft.jsch.Session.connect(Session.java:512)
06-14 19:22:13.964 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
06-14 19:22:13.964 13219 13219 W System.err: 	... 15 more
...
06-14 19:22:27.003 13219 13219 W System.err: org.eclipse.jgit.api.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:27.003 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
06-14 19:22:27.003 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.pushRepo(PushTask.java:109)
06-14 19:22:27.003 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:43)
06-14 19:22:27.003 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:24)
06-14 19:22:27.003 13219 13219 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
06-14 19:22:27.003 13219 13219 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-14 19:22:27.004 13219 13219 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-14 19:22:27.004 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-14 19:22:27.004 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-14 19:22:27.004 13219 13219 W System.err: 	at java.lang.Thread.run(Thread.java:761)
06-14 19:22:27.004 13219 13219 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:2206-14 19:22:13.962 13219 13219 W System.err: org.eclipse.jgit.api.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
06-14 19:22:13.963 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.pushRepo(PushTask.java:109)
06-14 19:22:13.963 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:43)
06-14 19:22:13.963 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:24)
06-14 19:22:13.963 13219 13219 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-14 19:22:13.963 13219 13219 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-14 19:22:13.963 13219 13219 W System.err: 	at java.lang.Thread.run(Thread.java:761)
06-14 19:22:13.963 13219 13219 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:320)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:166)
06-14 19:22:13.963 13219 13219 W System.err: 	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
06-14 19:22:13.964 13219 13219 W System.err: 	at org.eclipse.jgit.transport.Transport.push(Transport.java:1200)
06-14 19:22:13.964 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
06-14 19:22:13.964 13219 13219 W System.err: 	... 9 more
06-14 19:22:13.964 13219 13219 W System.err: Caused by: com.jcraft.jsch.JSchException: Auth fail
06-14 19:22:13.964 13219 13219 W System.err: 	at com.jcraft.jsch.Session.connect(Session.java:512)
06-14 19:22:13.964 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
06-14 19:22:13.964 13219 13219 W System.err: 	... 15 more
...
06-14 19:22:27.003 13219 13219 W System.err: org.eclipse.jgit.api.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:27.003 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
06-14 19:22:27.003 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.pushRepo(PushTask.java:109)
06-14 19:22:27.003 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:43)
06-14 19:22:27.003 13219 13219 W System.err: 	at me.sheimi.sgit.repo.tasks.repo.PushTask.doInBackground(PushTask.java:24)
06-14 19:22:27.003 13219 13219 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
06-14 19:22:27.003 13219 13219 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-14 19:22:27.004 13219 13219 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-14 19:22:27.004 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-14 19:22:27.004 13219 13219 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-14 19:22:27.004 13219 13219 W System.err: 	at java.lang.Thread.run(Thread.java:761)
06-14 19:22:27.004 13219 13219 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: ssh://me@192.1.2.3/home/me/repo/: Auth fail
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:320)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:166)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.Transport.push(Transport.java:1200)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
06-14 19:22:27.004 13219 13219 W System.err: 	... 9 more
06-14 19:22:27.004 13219 13219 W System.err: Caused by: com.jcraft.jsch.JSchException: Auth fail
06-14 19:22:27.004 13219 13219 W System.err: 	at com.jcraft.jsch.Session.connect(Session.java:512)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
06-14 19:22:27.005 13219 13219 W System.err: 	... 15 more
:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:320)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:166)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.Transport.push(Transport.java:1200)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
06-14 19:22:27.004 13219 13219 W System.err: 	... 9 more
06-14 19:22:27.004 13219 13219 W System.err: Caused by: com.jcraft.jsch.JSchException: Auth fail
06-14 19:22:27.004 13219 13219 W System.err: 	at com.jcraft.jsch.Session.connect(Session.java:512)
06-14 19:22:27.004 13219 13219 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
06-14 19:22:27.005 13219 13219 W System.err: 	... 15 more
```

`/home/me/repo/` is an empty, bare git repository.
Attempting to clone another repository from the PC results in the same error.
I can connect to the PC via ConnectBot using the same address (me@192.1.2.3) just fine.

Any idea what could be wrong?

**Comment by maks** [comment]
Thanks for reporting this.
Are you using a private key for your ssh login or just a username/password.
If the latter, then I think you are seeing the same issue as in #161
If thats the case, the work around is to use key based auth for your ssh login (thats the recommended best practise as well)

**Comment by uvok** [comment]
> Are you using a private key for your ssh login or just a username/password?

I tried to use username + password.

I now added an SSH key in mgit, added the public key to `~/.authorized_keys`, and now the pushing succeeds.
Thanks for the help.

**Comment by maks** [comment]
Thanks again for reporting back and glad the work around worked for you also. 
Again apologies for the issue, I'll try to get it fixed asap and have it down to work on for the next release.
