### ISSUE TITLE
Closing the editor leads to crash

### ISSUE THREAD

**Issue by armandbancila** [maks/MGit#182]
Closing CodeMirror makes the application crash.
# steps to reproduce
It happens when pressing 'back' while in editing mode, this immediately leads to a crash. Happens when I make modifications and even when I make no modifications. The crash first takes the app to the first activity and then the popup that shows 'has crashed' is displayed.

**Comment by maks** [comment]
Thank you for reporting the issue.
If possible, could you please include any extra information displayed when the app crashes?

**Comment by armandbancila** [comment]
There's no information included, just the standard error message from Android. 

Actually, now it looks like the bug has changed.
When I press on the back arrow, it says 'saved successfully' and it goes back to the list of repos, then the screen turns black and  "Complete action using" appears on the screen.

It only shows email apps. If I choose an email app I get an email with this body:

USER_COMMENT=
ANDROID_VERSION=6.0
APP_VERSION_NAME=1.5.3
BRAND=lge
PHONE_MODEL=LG-D855
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at me.sheimi.sgit.fragments.ViewFileFragment$CodeLoader.display(ViewFileFragment.java:198)
	at me.sheimi.sgit.fragments.ViewFileFragment$CodeLoader.access$600(ViewFileFragment.java:129)
	at me.sheimi.sgit.fragments.ViewFileFragment$CodeLoader$2.run(ViewFileFragment.java:186)
	at java.lang.Thread.run(Thread.java:818)

The files I'm opening have no extension but contain only text.

**Comment by maks** [comment]
Thank you for adding the extra information. The stack trace is the key piece, thats enough for me to find the issue and work on a fix.
