### ISSUE TITLE
Crash after go out of root directory

### ISSUE THREAD

**Issue by git001** [maks/MGit#199]
Akkording to the issue #198 is this the crash report which I have tried to send.

I was in the option -> main -> select root .

I was going back until '/' and pressed back again .
This "go out of root directory" causes this crash.

```
USER_COMMENT=
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=1.5.3
BRAND=OnePlus
PHONE_MODEL=ONE E1003
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File[] java.io.File.listFiles(java.io.FileFilter)' on a null object reference
at me.sheimi.sgit.adapters.FilesListAdapter.setDir(FilesListAdapter.java:71)
at me.sheimi.sgit.activities.explorer.FileExplorerActivity.setCurrentDir(FileExplorerActivity.java:107)
at me.sheimi.sgit.activities.explorer.FileExplorerActivity.onKeyUp(FileExplorerActivity.java:96)
at android.view.KeyEvent.dispatch(KeyEvent.java:2665)
at android.app.Activity.dispatchKeyEvent(Activity.java:2745)
at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2316)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4143)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4105)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3649)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3702)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3668)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3794)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3676)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3851)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3649)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3702)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3668)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3676)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3649)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3702)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3668)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3827)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3988)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2280)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1901)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1892)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2257)
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5539)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kaeptmblaubaer1000** [comment]
On some [java.io.File](https://www.tutorialspoint.com/java/io/java_io_file.htm) documentation, I've found out that `java.io.File.getParent()` returns a `null` `File` when you are in the `/` dir, after some code analysis on this repository I've found out that this even shouldn't be possible, but due to inconsistent usage of `dir == null` and `dir == mRootDir`, if you are in `mRootDir` and press back, the explorer quits.
But if you press `..` _when_ you are in `mRootDir`, this protection doesn't work anymore, because `mRootDir == dir`, which is used when you press back, isn't `true` and `FileListAdapter.setDir(null)` is called. That method invokes the method `listFiles` on the `null` value, which raises the `NullPointerException` and lets MGit crash.

**Comment by kaeptmblaubaer1000** [comment]
I think that it isn't good that users can't go beyond `/sdcard` (or whatever `Environment.getExternalStorageDir` returns), because that's the internal storage on at least my device, but I want to store my repositories on my SD card.

**Comment by maks** [comment]
@kaeptmblaubaer1000 you are right, the logic in FileExplorerActivity is pretty aweful, its just one more area of the app that needs complete overhaul.
Thanks for contributing a fix to the issue immediate crashing bug!
With using sdcards to store repos, thats a whole other can of worms that unfortunately cannot be addressed at the moment due to jgit not providing a was to abstract out file access needed on android to access sdcard storage, see issue #101 for more details.
