### ISSUE TITLE
mGit crashes at startup

### ISSUE THREAD

**Issue by uvok** [maks/MGit#200]
Hello,

mGit worked for a while, but today decided to stop working.
This is after updating to LineageOS 14.1-20170804 (Android 7.1.2), before, I had some July version running.
Not sure if the update has anything to do with it.
Phone is a Asus Zenfone Selfie / Z00UD
MGit version is 1.5.2 from F-Droid

The stack trace is
```
08-13 21:29:49.803  1185  3179 I ActivityManager: Start proc 9900:com.manichord.mgit/u0a111 for activity com.manichord.mgit/me.sheimi.sgit.RepoListActivity
08-13 21:29:49.848  1185  1292 E Notification: setLatestEventInfo() is deprecated and you should feel deprecated.
08-13 21:29:49.848  1185  1292 E Notification: java.lang.Throwable
08-13 21:29:49.848  1185  1292 E Notification: 	at android.app.Notification.setLatestEventInfo(Notification.java:2083)
08-13 21:29:49.848  1185  1292 E Notification: 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2363)
08-13 21:29:49.848  1185  1292 E Notification: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-13 21:29:49.848  1185  1292 E Notification: 	at android.os.Looper.loop(Looper.java:154)
08-13 21:29:49.848  1185  1292 E Notification: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-13 21:29:49.848  1185  1292 E Notification: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
08-13 21:29:49.878  9900  9900 I art     : Starting a blocking GC AddRemoveAppImageSpace
08-13 21:29:49.882  9900  9900 W System  : ClassLoader referenced unknown path: /data/app/com.manichord.mgit-1/lib/arm64
08-13 21:29:49.915  9900  9900 D AndroidRuntime: Shutting down VM
08-13 21:29:49.917  9900  9900 E AndroidRuntime: FATAL EXCEPTION: main
08-13 21:29:49.917  9900  9900 E AndroidRuntime: Process: com.manichord.mgit, PID: 9900
08-13 21:29:49.917  9900  9900 E AndroidRuntime: java.lang.RuntimeException: Unable to create application me.sheimi.sgit.SGitApplication: java.lang.UnsupportedOperationException
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at java.security.KeyStore.getEntry(KeyStore.java:1323)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at me.sheimi.android.utils.SecurePrefsHelper.<init>(SecurePrefsHelper.java:64)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at me.sheimi.sgit.SGitApplication.onCreate(SGitApplication.java:38)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
08-13 21:29:49.917  9900  9900 E AndroidRuntime: 	... 8 more
08-13 21:29:49.920  1185  1229 W ActivityManager:   Force finishing activity com.manichord.mgit/me.sheimi.sgit.RepoListActivity
08-13 21:29:49.931  9900  9900 I Process : Sending signal. PID: 9900 SIG: 9
08-13 21:29:49.955  1185  9624 I ActivityManager: Process com.manichord.mgit (pid 9900) has died
08-13 21:29:49.956  1185  9624 D ActivityManager: cleanUpApplicationRecord -- 9900
```

**Comment by uvok** [comment]
Also, for some strange reason, after backing up app+data with TitaniumBackup, uninstalling the app, and restoring app+data, the app starts again.

**Comment by maks** [comment]
This should have been fixed. Please reopen if issue is still occurring
