### ISSUE TITLE
An exception on start

### ISSUE THREAD

**Issue by KOLANICH** [maks/MGit#237]
```
--------- beginning of /dev/log/main
D/su      ( 4791): 0 /system/bin/mksh executing 10090 logcat using binary /system/bin/sh : sh -c logcat
E/dalvikvm( 4796): Dex cache directory isn't writable: /data/dalvik-cache
I/dalvikvm( 4796): Unable to open or create cache for /data/app/com.manichord.mgit_204.apk (/data/dalvik-cache/data@app@com.manichord.mgit_204.apk@classes.dex)
W/XPrivacy( 4796): Hooking package=com.manichord.mgit
D/ActivityThread( 4796): handleBindApplication:com.manichord.mgit
D/ActivityThread( 4796): setTargetHeapUtilization:0.75
D/ActivityThread( 4796): setTargetHeapMinFree:2097152
D/AndroidRuntime( 4796): Shutting down VM
W/dalvikvm( 4796): threadid=1: thread exiting with uncaught exception (group=0x4160ace0)
--------- beginning of /dev/log/system
E/AndroidRuntime( 4796): FATAL EXCEPTION: main
E/AndroidRuntime( 4796): Process: com.manichord.mgit, PID: 4796
E/AndroidRuntime( 4796): java.lang.RuntimeException: Unable to instantiate application me.sheimi.sgit.SGitApplication: java.lang.ClassNotFoundException: Didn't find class "me.sheimi.sgit.SGitApplication" on path: DexPathList[[zip file "/data/app/com.manichord.mgit_204.apk"],nativeLibraryDirectories=[/data/app-lib/com.manichord.mgit_204, /vendor/lib, /system/lib]]
E/AndroidRuntime( 4796): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:514)
E/AndroidRuntime( 4796): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4446)
E/AndroidRuntime( 4796): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4796): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime( 4796): 	at android.app.ActivityThread.handleBindApplication(Native Method)
E/AndroidRuntime( 4796): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
E/AndroidRuntime( 4796): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
E/AndroidRuntime( 4796): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4796): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4796): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime( 4796): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4796): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4796): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 4796): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 4796): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 4796): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4796): Caused by: java.lang.ClassNotFoundException: Didn't find class "me.sheimi.sgit.SGitApplication" on path: DexPathList[[zip file "/data/app/com.manichord.mgit_204.apk"],nativeLibraryDirectories=[/data/app-lib/com.manichord.mgit_204, /vendor/lib, /system/lib]]
E/AndroidRuntime( 4796): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 4796): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 4796): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 4796): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/AndroidRuntime( 4796): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
E/AndroidRuntime( 4796): 	... 15 more
E/AndroidRuntime( 4796): 	Suppressed: java.io.IOException: unable to open DEX file
E/AndroidRuntime( 4796): 		at dalvik.system.DexFile.openDexFileNative(Native Method)
E/AndroidRuntime( 4796): 		at dalvik.system.DexFile.openDexFile(DexFile.java:296)
E/AndroidRuntime( 4796): 		at dalvik.system.DexFile.<init>(DexFile.java:80)
E/AndroidRuntime( 4796): 		at dalvik.system.DexFile.<init>(DexFile.java:59)
E/AndroidRuntime( 4796): 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:263)
E/AndroidRuntime( 4796): 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
E/AndroidRuntime( 4796): 		at dalvik.system.DexPathList.<init>(DexPathList.java:112)
E/AndroidRuntime( 4796): 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
E/AndroidRuntime( 4796): 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
E/AndroidRuntime( 4796): 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
E/AndroidRuntime( 4796): 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:321)
E/AndroidRuntime( 4796): 		at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:205)
E/AndroidRuntime( 4796): 		at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
E/AndroidRuntime( 4796): 		... 12 more
I/Process ( 4796): Sending signal. PID: 4796 SIG: 9
```

**Comment by maks** [comment]
Thank you for reporting this, but from the exception stack trace, this appears to be a problem within the Android framework so I'm unable to help with it. Given you are using Xposed I would suggest contacting the Xposed developers for further assistance.
