### ISSUE TITLE
Mgit error

### ISSUE THREAD

**Issue by Kenedy89** [maks/MGit#247]
USER_COMMENT=
ANDROID_VERSION=4.4.4
APP_VERSION_NAME=1.5.3
BRAND=samsung
PHONE_MODEL=SM-T116NU
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at me.sheimi.sgit.adapters.FilesListAdapter.setDir(FilesListAdapter.java:71)
at me.sheimi.sgit.activities.explorer.FileExplorerActivity.setCurrentDir(FileExplorerActivity.java:107)
at me.sheimi.sgit.activities.explorer.FileExplorerActivity.onKeyUp(FileExplorerActivity.java:96)
at android.view.KeyEvent.dispatch(KeyEvent.java:3232)
at android.app.Activity.dispatchKeyEvent(Activity.java:2517)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2110)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4119)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3792)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3849)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3825)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2107)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1755)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1746)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2084)
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:5584)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)

TURNIP

**Comment by maks** [comment]
Thank you for reporting the issue.
Could you please let me know what you were trying to do when the error occurred?

**Comment by Kenedy89** [comment]
I try to manage ssh key!!
But till now i'm still confused  what happend to my tab, it's a problem with apache.org if i join on github?
What i must to do if that's problem with licency on my phone?

**Comment by kaeptmblaubaer1000** [comment]
Duplicate of #199

**Comment by maks** [comment]
And of #326
