### ISSUE TITLE
Repository detail screen (RepoDetailActivity) crashes immediately on Android 6.0 (MGit 1.5.4)

### ISSUE THREAD

**Issue by muojp** [maks/MGit#280]
## What happens

DESIRED: Repository detail screen shows up when tapping a repository name on repository-list screen
ACTUAL: Crash reporting screen (Gmail draft) shows up immediately

Device: Lenovo Phab 2 Pro
OS version: Android 6.0.1 (API Level 23)

## How to reproduce

I ran across with this issue on cloned repositories but I confirmed it also happen on local repositories.

1. Create an emulator image w/ Android 6.0.0
2. Build https://github.com/maks/MGit/tree/v1.5.4 tree and run the app on the emulator
3. Menu -> Clone
4. Tap `INIT LOCAL`
5. put `test` as local Path (repository name)
6. Tap `INIT`
7. Tap `test` repository -> MGit Crashes

## Quick guess

Repository detail screen (RepoDetailActivity) crashes immediately on my device since last night. So I guess something went wrong on 1.5.4.

Crash log says NullPointerException occurred at https://github.com/maks/MGit/blob/master/app/src/main/java/me/sheimi/sgit/activities/RepoDetailActivity.java#L156

I haven't explored the source well but I noticed null-guard for action-bar was added for FileExplorerActivity ( https://github.com/maks/MGit/commit/4ee9d5d583cafc9ef9a9fa8358952807d0b9c0c0 ) so similar changes need to be performed on other activities.

**Comment by superfury** [comment]
Got such a problem as well, clicking my old existing repository. Mail content:
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.5.4
BRAND=samsung
PHONE_MODEL=SM-G930F
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.manichord.mgit/me.sheimi.sgit.activities.RepoDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayShowTitleEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayShowTitleEnabled(boolean)' on a null object reference
	at me.sheimi.sgit.activities.RepoDetailActivity.setupActionBar(RepoDetailActivity.java:156)
	at me.sheimi.sgit.activities.RepoDetailActivity.onCreate(RepoDetailActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:6912)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayShowTitleEnabled(boolean)' on a null object reference
	at me.sheimi.sgit.activities.RepoDetailActivity.setupActionBar(RepoDetailActivity.java:156)
	at me.sheimi.sgit.activities.RepoDetailActivity.onCreate(RepoDetailActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:6912)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by muojp** [comment]
Confirmed fix. Great work, @mikica1986vee !
