### ISSUE TITLE
MGit 1.5.4.1 crashes on commit details and unstaged diff

### ISSUE THREAD

**Issue by mvbasov** [maks/MGit#283]
Upgrade 1.5.3 to 1.5.4.1 from play market

USER_COMMENT=
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=1.5.4.1
BRAND=Xiaomi
PHONE_MODEL=MI 5s
CUSTOM_DATA=
STACK_TRACE=java.lang.UnsupportedOperationException: This is not supported, use MenuItemCompat.getActionProvider()
	at android.support.v7.view.menu.MenuItemImpl.getActionProvider(MenuItemImpl.java:648)
	at me.sheimi.sgit.activities.CommitDiffActivity.onCreateOptionsMenu(CommitDiffActivity.java:107)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3146)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:362)
	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
	at android.support.v7.app.AppCompatDelegateImplV9.preparePanel(AppCompatDelegateImplV9.java:1361)
	at android.support.v7.app.AppCompatDelegateImplV9.doInvalidatePanelMenu(AppCompatDelegateImplV9.java:1641)
	at android.support.v7.app.AppCompatDelegateImplV9$1.run(AppCompatDelegateImplV9.java:136)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by maks** [comment]
Thanks for reporting this, I'll get a fix out for this tomorrow. Apologies for the hassles with these breaking changes.
