### ISSUE TITLE
crash on Android when attempting to edit file

### ISSUE THREAD

**Issue by maks** [maks/MGit#319]
USER_COMMENT=
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=1.5.4.2
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A5000
CUSTOM_DATA=
STACK_TRACE=android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.manichord.mgit/files/repo/MGit/README.md exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
at android.net.Uri.checkFileUriExposed(Uri.java:2348)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9766)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1795)
at android.app.Activity.startActivityForResult(Activity.java:4495)
at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
at android.app.Activity.startActivityForResult(Activity.java:4453)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
at android.app.Activity.startActivity(Activity.java:4814)
at android.app.Activity.startActivity(Activity.java:4782)
at me.sheimi.android.activities.SheimiFragmentActivity.startActivity(SheimiFragmentActivity.java:232)
at me.sheimi.sgit.activities.ViewFileActivity.onOptionsItemSelected(ViewFileActivity.java:226)
at android.app.Activity.onMenuItemSelected(Activity.java:3458)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:675)
at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
at android.widget.AdapterView.performItemClick(AdapterView.java:318)
at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3166)
at android.widget.AbsListView$3.run(AbsListView.java:4119)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6809)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by muojp** [comment]
@maks hi. I love MGit and I use it on the daily basis. I recently purchased a new phone (Android 9.0) and found `Edit in other apps` feature is broken like described here. Could you take a look at the pull-req #415 I composed for this issue, please?

**Comment by GerkinDev** [comment]
Hi,
I'm still experiencing the issue, even if #415 have been merged. Have you released a new version?

**Comment by maks** [comment]
This is working for me on current master, which will be in the next release coming out shortly.
