### ISSUE TITLE
MGit crashes after a minute when opening git/git

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [maks/MGit#346]
This is an OutOfMemoryError related to the _large_ history.

My thoughts how to solve this:
We shouldn't keep the whole history in memory.
Maybe we could use a backtracking dynamic linked list. Linked based on the `parent` entry of commits and to solve performance problems, backtracking because there's no `child` entry and dynamic because only one block is hold in-memory and each block is computed just-in-time.

**Comment by kaeptmblaubaer1000** [comment]
I don't know (but i think) that JGit has a low-level API suitable for this.

**Comment by maks** [comment]
@kaeptmblaubaer1000 please include a stacktrace if possible.

And please be more specific, is this occurring during cloning? Or after a successful clone when opening the local repo.

However given its `git/git` I would expect this to actually be a duplicate of #54 which covers the problem of cloning large repos. In that case its a **JGit** issue rather than any implementation details you speculate on. Please see https://github.com/maks/MGit/issues/54#issuecomment-257765702 for more information on how JGit already implements a **streaming** mode to deal with large repos.

**Comment by kaeptmblaubaer1000** [comment]
@maks it's the log. I've cloned using C Git.
Stacktrace:
```
java.lang.OutOfMemoryError
at java.util.ArrayList.toArray(ArrayList.java:492)
at java.util.ArrayList.<init>(ArrayList.java:93)
at me.sheimi.sgit.adapters.CommitsListAdapter$1.postCommits(CommitsListAdapter.java:289)
at me.sheimi.sgit.repo.tasks.repo.GetCommitTask.onPostExecute(GetCommitTask.java:41)
at me.sheimi.sgit.repo.tasks.repo.GetCommitTask.onPostExecute(GetCommitTask.java:13)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
```
