### ISSUE TITLE
Slow and buggy on big repos

### ISSUE THREAD

**Issue by cyberb** [maks/MGit#347]
On big repos more than 25k commits (https://github.com/syncloud/snapd)
Frequently getting this exception while doing different things, changing, committing, pushing..
I am using external editor Droid Edit app.

````
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.5.4.2
BRAND=motorola
PHONE_MODEL=Moto G (4)
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689659, class android.widget.ListView) with Adapter(class me.sheimi.sgit.adapters.CommitsListAdapter)]
at android.widget.ListView.layoutChildren(ListView.java:1618)
at android.widget.AbsListView$CheckForTap.run(AbsListView.java:3461)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by kaeptmblaubaer1000** [comment]
Similar to #346, but different exception.

**Comment by maks** [comment]
@kaeptmblaubaer1000 this is *not* related to 346, please see my comments there.

In regards to this issue, we need to support proper paging for dealing with large histories. Switching over to RecyclerView is already on my todo list and will have in having a better implementation to deal with this also.
