### ISSUE TITLE
crash reported from acra: JGitInternalException: Creating directories for /storage/emulated/0/MGit/.git failed

### ISSUE THREAD

**Issue by maks** [maks/MGit#366]
```
USER_COMMENT=
ANDROID_VERSION=8.1.0
APP_VERSION_NAME=1.5.4.4
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A5000
CUSTOM_DATA=
STACK_TRACE=org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /storage/emulated/0/MGit/.git failed
at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:118)
at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:161)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:69)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:36)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:21)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: Creating directories for /storage/emulated/0/MGit/.git failed
at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:316)
at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:271)
at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:115)
... 11 more
java.io.IOException: Creating directories for /storage/emulated/0/MGit/.git failed
at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:316)
at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:271)
at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:115)
at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:161)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:69)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:36)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:21)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by maks** [comment]
Because we are now targetting SKD 27 we need to request write permission dynamically from the user. Currently users on Andriod >= 6.0 are having to work around this themeselves by going into system settings and explicitly granting storage write permission, but obviously the app needs to be doing this itself properly.

**Comment by kaeptmblaubaer1000** [comment]
@maks there are several other issues that report this, please close them too.
