### ISSUE TITLE
Error on opening a file in external editor [intermittent]

### ISSUE THREAD

**Issue by cyberb** [maks/MGit#383]
````
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.5.4.5
BRAND=motorola
PHONE_MODEL=Moto G (4)
CUSTOM_DATA=
STACK_TRACE=org.eclipse.jgit.api.errors.JGitInternalException: Missing tree 896fc0ccab86233fadd7e4d083eee3cb2eaf54e2
at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:154)
at me.sheimi.sgit.repo.tasks.repo.StatusTask.status(StatusTask.java:43)
at me.sheimi.sgit.repo.tasks.repo.StatusTask.doInBackground(StatusTask.java:27)
at me.sheimi.sgit.repo.tasks.repo.StatusTask.doInBackground(StatusTask.java:11)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing tree 896fc0ccab86233fadd7e4d083eee3cb2eaf54e2
at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:149)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:202)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator0(CanonicalTreeParser.java:236)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:214)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:60)
at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:912)
at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:566)
at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:432)
at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:374)
at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:148)
... 9 more
org.eclipse.jgit.errors.MissingObjectException: Missing tree 896fc0ccab86233fadd7e4d083eee3cb2eaf54e2
at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:149)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:202)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator0(CanonicalTreeParser.java:236)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:214)
at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:60)
at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:912)
at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:566)
at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:432)
at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:374)
at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:148)
at me.sheimi.sgit.repo.tasks.repo.StatusTask.status(StatusTask.java:43)
at me.sheimi.sgit.repo.tasks.repo.StatusTask.doInBackground(StatusTask.java:27)
at me.sheimi.sgit.repo.tasks.repo.StatusTask.doInBackground(StatusTask.java:11)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
````

**Comment by kaeptmblaubaer1000** [comment]
@cyberb this is related to the "Status" tab loading in the background.
Your repository is incomplete.

**Comment by cyberb** [comment]
Do you have more than one thread doing interdependent tasks?
should file open task wait for the load or at least say it is loading?

**Comment by maks** [comment]
The current implementation of Async tasks and long running operations is sadly a bit of a mess. It's on my to-do list to refactor it and use Rx for all Async code and do long running operations with std notification UI for user feedback.

**Comment by cyberb** [comment]
@kaeptmblaubaer1000 forgot to mention that repo was fine after reopening the app.
So looking at it right now this looks to me as a bug in jgit.
Unless tasks are breaking it somehow.
Looking at execute call
https://github.com/maks/MGit/blob/master/app/src/main/java/me/sheimi/sgit/repo/tasks/repo/StatusTask.java#L38
it is clear that app is using default executor which is serial executor according to android docs:
https://android.googlesource.com/platform/frameworks/base.git/+/master/core/java/android/os/AsyncTask.java#224

Unless somewhere else we are calling jgit from other threads like main. 
But again jgit people say that it is thread safe unless you are using a working directory.
https://dev.eclipse.org/mhonarc/lists/jgit-dev/msg02128.html

So what I am trying to say, do not change threading model unless you understand what exactly is causing this or other similar issues. Rx will not give you more understanding of what is happening with your threads, it usually makes it much more complex as each call on Rx api may change threads (unless you carefully control that). At least that is my experience.

**Comment by maks** [comment]
@cyberb I'd expect it to work fine after reopening the app if it's *is* a thread/race condition. That's what's I meant in my previous comment: UI in android always breeds to happen on main thread, IO always of it, so there can always be threading issues and jgit being "thread safe" is irrelevant to those problems as we do not serialise access to the working dir via jgit and even if we did that would not help as pointed out by Shawn in the email link you provided.
