### ISSUE TITLE
Pull fails sometimes

### ISSUE THREAD

**Issue by cyberb** [maks/MGit#407]
Pull fails, but second attempt succeeds.

````
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.5.4.6
BRAND=motorola
PHONE_MODEL=Moto G (4)
CUSTOM_DATA=
STACK_TRACE=org.eclipse.jgit.api.errors.TransportException: Could not delete file /storage/emulated/0/Android/data/com.manichord.mgit/files/repo/platform/.git/objects/pack/pack-bcbed5fa07b3367e28b540c2f2b8c26767cd1351.keep
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
at me.sheimi.sgit.repo.tasks.repo.PullTask.pullRepo(PullTask.java:99)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:30)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:15)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: org.eclipse.jgit.errors.TransportException: Could not delete file /storage/emulated/0/Android/data/com.manichord.mgit/files/repo/platform/.git/objects/pack/pack-bcbed5fa07b3367e28b540c2f2b8c26767cd1351.keep
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:128)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
... 10 more
Caused by: java.io.IOException: Could not delete file /storage/emulated/0/Android/data/com.manichord.mgit/files/repo/platform/.git/objects/pack/pack-bcbed5fa07b3367e28b540c2f2b8c26767cd1351.keep
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:181)
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:109)
at org.eclipse.jgit.internal.storage.file.PackLock.unlock(PackLock.java:101)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:126)
... 12 more
org.eclipse.jgit.errors.TransportException: Could not delete file /storage/emulated/0/Android/data/com.manichord.mgit/files/repo/platform/.git/objects/pack/pack-bcbed5fa07b3367e28b540c2f2b8c26767cd1351.keep
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:128)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
at me.sheimi.sgit.repo.tasks.repo.PullTask.pullRepo(PullTask.java:99)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:30)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:15)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.io.IOException: Could not delete file /storage/emulated/0/Android/data/com.manichord.mgit/files/repo/platform/.git/objects/pack/pack-bcbed5fa07b3367e28b540c2f2b8c26767cd1351.keep
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:181)
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:109)
at org.eclipse.jgit.internal.storage.file.PackLock.unlock(PackLock.java:101)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:126)
... 12 more
java.io.IOException: Could not delete file /storage/emulated/0/Android/data/com.manichord.mgit/files/repo/platform/.git/objects/pack/pack-bcbed5fa07b3367e28b540c2f2b8c26767cd1351.keep
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:181)
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:109)
at org.eclipse.jgit.internal.storage.file.PackLock.unlock(PackLock.java:101)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:126)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
at me.sheimi.sgit.repo.tasks.repo.PullTask.pullRepo(PullTask.java:99)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:30)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:15)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
````

**Comment by maks** [comment]
thanks for reporting this, I cant see why the delete would be failing unless the file had already been deleted which would indicate a race-condition bug in jgit perhaps.
