### ISSUE TITLE
Can't Clon

### ISSUE THREAD

**Issue by timmy61109** [maks/MGit#428]
### Error message:
USER_COMMENT=
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=1.5.4.7
BRAND=asus
PHONE_MODEL=ASUS_Z01KD
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Inflater has been closed
at java.util.zip.Inflater.ensureOpen(Inflater.java:400)
at java.util.zip.Inflater.reset(Inflater.java:354)
at org.eclipse.jgit.lib.InflaterCache.release(InflaterCache.java:92)
at org.eclipse.jgit.internal.storage.file.WindowCursor.release(WindowCursor.java:371)
at org.eclipse.jgit.internal.storage.file.PackInputStream.close(PackInputStream.java:83)
at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:239)
at java.io.BufferedInputStream.close(BufferedInputStream.java:485)
at org.eclipse.jgit.lib.ObjectStream$Filter.close(ObjectStream.java:229)
at org.eclipse.jgit.lib.ObjectLoader.copyTo(ObjectLoader.java:268)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1244)
at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:451)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:251)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by kaeptmblaubaer1000** [comment]
@timmy61109 we need more information. Did you use an SSH url? SGit (MGit is the successor of SGit) had such an issue in the past (sheimi/SGit#65), I don't know whether it's fixed.

**Comment by timmy61109** [comment]
I know why there is no way to clone, because I set the path on the SD card, but because the program does not support saving to external space, an error occurs, I hope this can be resolved.

**Comment by kb-1000** [comment]
That would be very interesting, as the file manager that is used to select the directory could not access external space then either.

**Comment by timmy61109** [comment]
Can this problem be solved?

**Comment by maks** [comment]
Sorry to take so long to respond. This maybe due to an existing issue which causes an error after switching MGit's root storage folder.

**Comment by timmy61109** [comment]
> Sorry to take so long to respond. This maybe due to an existing issue which causes an error after switching MGit's root storage folder.

Thak you!

**Comment by non-Jedi** [comment]
After getting mgit working from #491, I'm running into this same stack-trace when cloning a repo over ssh. The only special thing about the repo in question is that it's using git-lfs which I know mgit doesn't support, but I should still be able to clone the repo and just not access those files. Let me know if there's any additional info I can provide to help.

**Comment by maks** [comment]
@non-Jedi I'm actually not certain what the expected behaviour for Mgit and the old version of JGit we use is for repos using LFS, I'll look into it.

**Comment by non-Jedi** [comment]
For what it's worth, on desktop without git-lfs installed, you can successfully clone an lfs repository (e.g. https://stackoverflow.com/questions/39691929/can-one-clone-a-git-lfs-repo-without-installing-git-lfs). You only run into issues when trying to checkout a branch (which clone obviously does automatically). This crash occurs during clone, so it was my assumption that it was unrelated to lfs since the lfs filter shouldn't run at that time (lfs files are simply encoded as a kind of text pointer).
