### ISSUE TITLE
Conflict issue

### ISSUE THREAD

**Issue by lhwdev** [maks/MGit#429]
It has conflict with its remote, but it doesn't show conflect files on status panel or anywhere, just an exception.

```
STACK_TRACE=org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
---some files in github lhwdev/ASM-preview
at org.eclipse.jgit.api.MergeCommand.call(MergeCommand.java:411)
at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:322)
at me.sheimi.sgit.repo.tasks.repo.PullTask.pullRepo(PullTask.java:99)
**at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:30)**
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:15)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
---PRIVACY(?)---
at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:415)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
at org.eclipse.jgit.api.MergeCommand.call(MergeCommand.java:288)
... 10 more
org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
---privacy v2---
at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:415)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
at org.eclipse.jgit.api.MergeCommand.call(MergeCommand.java:288)
at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:322)
at me.sheimi.sgit.repo.tasks.repo.PullTask.pullRepo(PullTask.java:99)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:30)
at me.sheimi.sgit.repo.tasks.repo.PullTask.doInBackground(PullTask.java:15)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```

+Also, why don't you use proguard? (or because of bug?..) It will make your app run faster(I don't sure it will) and apk size will be reduced. `invoke-static {v0} a->a(I)V` will be better than `invoke-static {v0} com/myapp/myproject/MyApp->hello(I)V`

**Comment by suphm** [comment]
needs a  conflict resolver
