### ISSUE TITLE
MGit crashes if opening a pdf.

### ISSUE THREAD

**Issue by mbaeten** [maks/MGit#432]
Somehow related to #268 #219. When opening a pdf, the app crashes instead of opening it (with the correct app).

USER_COMMENT=
ANDROID_VERSION=8.1.0
APP_VERSION_NAME=1.5.4.7
BRAND=samsung
PHONE_MODEL=SM-G900F
CUSTOM_DATA=
STACK_TRACE=android.os.FileUriExposedException: file:///storage/emulated/0/git-repos/someRepo/some.pdf exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
at android.net.Uri.checkFileUriExposed(Uri.java:2356)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9881)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9856)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
at android.app.Activity.startActivityForResult(Activity.java:4487)
at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
at android.app.Activity.startActivityForResult(Activity.java:4445)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
at android.app.Activity.startActivity(Activity.java:4806)
at android.app.Activity.startActivity(Activity.java:4774)
at me.sheimi.android.activities.SheimiFragmentActivity.startActivity(SheimiFragmentActivity.java:262)
at me.sheimi.android.utils.FsUtils.openFile(FsUtils.java:131)
at me.sheimi.android.utils.FsUtils.openFile(FsUtils.java:120)
at me.sheimi.sgit.fragments.FilesFragment$2.onItemClick(FilesFragment.java:100)
at android.widget.AdapterView.performItemClick(AdapterView.java:318)
at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
at android.widget.AbsListView$3.run(AbsListView.java:4042)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by maks** [comment]
My apologies for not getting to this sooner. Yes this is fixed by:  https://github.com/maks/MGit/commit/b4213fe5be12112e6a28f9f832c8af97ffc47ff5
I'll try to get a release out in the next couple of days.

**Comment by mbaeten** [comment]
No need to apologize, it's your spare time, isn't it? ;)

**Comment by maks** [comment]
Yes indeed it is and I have unfortunately not had much spare time in last few months to work on MGit. I'm hoping that will change soon.
I meantime the fix (via 241572ce6844933f312ca2a865dcf3e2e5aed196)  is now released in a new version on Play (Beta channel) and if no issues with Beta will go out to all users soon after.

**Comment by maks** [comment]
Unfortunately still broken :-(
Thanks @kaeptmblaubaer1000 for sending thru the report

```
USER_COMMENT=It is still broken
ANDROID_VERSION=8.1.0
APP_VERSION_NAME=1.5.5
BRAND=bq
PHONE_MODEL=Aquaris X Pro
CUSTOM_DATA=
STACK_TRACE=android.os.FileUriExposedException: file:///storage/emulated/0/ZZZZZZZZZZZZZZZ exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
at android.net.Uri.checkFileUriExposed(Uri.java:2356)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9884)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9859)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9838)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1612)
at android.app.Activity.startActivityForResult(Activity.java:4501)
at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
at android.app.Activity.startActivityForResult(Activity.java:4459)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
at android.app.Activity.startActivity(Activity.java:4820)
at android.app.Activity.startActivity(Activity.java:4788)
at me.sheimi.android.activities.SheimiFragmentActivity.startActivity(SheimiFragmentActivity.java:262)
at me.sheimi.android.utils.FsUtils.openFile(FsUtils.java:131)
at me.sheimi.android.utils.FsUtils.openFile(FsUtils.java:120)
at me.sheimi.sgit.fragments.FilesFragment$2.onItemClick(FilesFragment.java:100)
at android.widget.AdapterView.performItemClick(AdapterView.java:318)
at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3150)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6543)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by maks** [comment]
ok so sadly this is because the fix simply created private methods in ViewFileActivity without realising there was also an implementation in FsUtils that continued to be in use.
All need to fix this properly and do a new release.
