### ISSUE TITLE
Clone over SSH failed.

### ISSUE THREAD

**Issue by RB-Lab** [maks/MGit#446]
Hello, and thanks for the app (even though, I didn't have a chance to enjoyed it yet)!

I tried to clone a repo from the private server via SSH, using a key, generated inside the app (Settings -> SSH keys -> Generate key (I used RSA 4096)). The app failed with the view pretty similar to one in #428. 

Though stack trace looks a bit different, therefore I report it as a different issue. 

I can say that cloning the same repo (with a different key, of course) works well on my PC with git version 2.17.1. I also can say that I definitely added the public key into my `.ssh/authorized_keys` on my server. The app was installed from F-Droid, if it matters.

Stack trace/error report (I replaced my host and path with `***` due to paranoia):
```
USER_COMMENT=
ANDROID_VERSION=8.1.0
APP_VERSION_NAME=1.5.5.1
BRAND=asus
PHONE_MODEL=ZB602KL
CUSTOM_DATA=
STACK_TRACE=org.eclipse.jgit.api.errors.TransportException: ssh://***/home/***.git: Auth cancel
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://******/home/***.git: Auth cancel
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
... 11 more
Caused by: com.jcraft.jsch.JSchException: Auth cancel
at com.jcraft.jsch.Session.connect(Session.java:518)
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
... 18 more
org.eclipse.jgit.errors.TransportException: ssh://****/home/***.git: Auth cancel
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: com.jcraft.jsch.JSchException: Auth cancel
at com.jcraft.jsch.Session.connect(Session.java:518)
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
... 18 more
com.jcraft.jsch.JSchException: Auth cancel
at com.jcraft.jsch.Session.connect(Session.java:518)
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```
I would be happy to elaborate on the problem, though I'm pretty much know nothing on Android.

**Comment by maks** [comment]
Sorry for the slow response.
If you have a known working key, could you try using it with MGit? Brief instructions for [importing a ssh key into MGit are in the faq](https://github.com/maks/MGit/wiki/faq#how-do-i-use-a-ssh-certificate)

**Comment by RB-Lab** [comment]
Sorry, I don't remember even why I tried to use the app, and what was the overall environment. It's probably better to close the issue: I doubt that I could reproduce anything in the near future..
