### ISSUE TITLE
Clone Failed (Inflater)

### ISSUE THREAD

**Issue by Joncom** [maks/MGit#459]
Clone gets about 50% and then crashes:

```
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.5.5.1
BRAND=samsung
PHONE_MODEL=SM-G920F
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Inflater has been closed
at java.util.zip.Inflater.ensureOpen(Inflater.java:397)
at java.util.zip.Inflater.reset(Inflater.java:352)
at org.eclipse.jgit.lib.InflaterCache.release(InflaterCache.java:92)
at org.eclipse.jgit.internal.storage.file.WindowCursor.release(WindowCursor.java:371)
at org.eclipse.jgit.internal.storage.file.PackInputStream.close(PackInputStream.java:83)
at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:232)
at java.io.BufferedInputStream.close(BufferedInputStream.java:472)
at org.eclipse.jgit.lib.ObjectStream$Filter.close(ObjectStream.java:229)
at org.eclipse.jgit.lib.ObjectLoader.copyTo(ObjectLoader.java:268)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1244)
at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:451)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:251)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
```

**Comment by kb-1000** [comment]
Can you give more information? Like the repository you tried to clone?

**Comment by Joncom** [comment]
It's a private repo, about 900 MB in size, and contains a lot of binary
image files.

**Comment by Joncom** [comment]
I read somewhere that Git likes to put the entire repo in memory when cloning. Could this be an issue of running out of memory due to the repo size?

**Comment by kb-1000** [comment]
How much RAM memory does your Android device have?

**Comment by Joncom** [comment]
Never mind. Thought it had 1 GB. But it actually has 3 GB.

**Comment by maks** [comment]
MGit, has [known long-standing problem with cloning large repos](https://github.com/maks/MGit/issues/54). There is actually explicit support for streaming git repos within jgit so there is not infact a hard requirement to keep the whole repo in-memory but I have not had time to go back to look into that yet.

**Comment by Joncom** [comment]
Seems like a mistake to close this.

That does not sound like the same issue. That issue finishes cloning with
no error message, but an empty repo. This issue fails with an error
message.

Additionally, as was noted above, whether or not the entire repo can fit
into memory is not relevant here, because the issue device has way more
than necessary memory.

**Comment by maks** [comment]
@Joncom its a variation of the same bug. In this case, it just so happens that the low-memory condition is triggering GC which causes this exception which itself is most likely a [java class library bug], (https://issues.apache.org/jira/browse/FELIX-1032?focusedCommentId=12724313&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12724313)

But the root cause is still lack of memory. Your assumption that:
>device has way more than necessary memory

however is quite incorrect. 
On Android devices, apps running in a Dalvik VM are limited to the amount of heap space they can access. This varies by Android version and OEM device settings, but *best* case is likely to be 512-1024MB. It definitely will *not* be any where near the amount of total RAM your device has.

This limit on heap space has been [documented](https://developer.android.com/topic/performance/memory-overview#RestrictingMemory) and [thoroughly discussed](https://stackoverflow.com/questions/5350465/android-heap-size-on-different-phones-devices-and-os-versions)

If you are interested, you can use a "system view" app or the [adb command line ](https://stackoverflow.com/a/10696146/85472) to determine the max heap setting for your device.
