### ISSUE TITLE
java.lang.IllegalStateException: (context as Activity).currentFocus must not be null

### ISSUE THREAD

**Issue by 532910** [maks/MGit#486]
Just a copy of Crash Report send via e-mail 2019-02-11 and left without response.

```
USER_COMMENT= clone -> cancel
ANDROID_VERSION=8.1.0
APP_VERSION_NAME=1.5.4.7
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A3010
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: (context as Activity).currentFocus must not be null
at com.manichord.mgit.ViewHelperKt.hideKeyboard(ViewHelper.kt:9)
at com.manichord.mgit.repolist.RepoListActivity.hideCloneView(RepoListActivity.java:269)
at com.manichord.mgit.repolist.RepoListActivity.access$100(RepoListActivity.java:48)
at com.manichord.mgit.repolist.RepoListActivity$1.onActionClick(RepoListActivity.java:80)
at me.sheimi.sgit.databinding.CloneViewBinding._internalCallbackOnClick(CloneViewBinding.java:545)
at android.databinding.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
at android.view.View.performClick(View.java:6294)
at android.view.View$PerformClick.run(View.java:24770)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by maks** [comment]
Thanks you for submitting this. Yes definitely a bug that needs fixing.
