### ISSUE TITLE
Unable to clone over ssh

### ISSUE THREAD

**Issue by non-Jedi** [maks/MGit#491]
I am consistently unable to clone repos over ssh from my gitea server. If I use a key generated on a computer and imported to mgit, it works fine on computer but fails with mgit.

```
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.5.5.1
BRAND=samsung
PHONE_MODEL=SM-G930U
CUSTOM_DATA=
STACK_TRACE=org.eclipse.jgit.api.errors.TransportException: ssh://_gitea@home.thebeckmeyers.xyz:9999/adam/org.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://_gitea@home.thebeckmeyers.xyz:9999/adam/org.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 11 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 18 more
org.eclipse.jgit.errors.TransportException: ssh://_gitea@home.thebeckmeyers.xyz:9999/adam/org.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 18 more
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
	at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
```

**Comment by kb-1000** [comment]
What settings does the key have?

**Comment by non-Jedi** [comment]
RSA 4096 bits with no password. I can try with a 2048 RSA if you think that would make a difference.

**Comment by maks** [comment]
@non-Jedi That might be worth trying. MGit via JGit use [Jsch](http://www.jcraft.com/jsch/) for SSH connections so might be worth having a look at what Jsch supports in terms of SSH keys.

**Comment by non-Jedi** [comment]
As additional info, [Android Password Store](https://github.com/android-password-store/Android-Password-Store) works fine on this device which I believe also uses JGit. I will try a 2048-bit and report back.
